services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        ports: 
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - teastream-backend

volumes:
    postgres_data:
    redis_data:

networks:
    teastream-backend:
